#!/bin/bash

set -e

d=`realpath "$(dirname "${0}")"`
tmprepo="${d}/repo"
tmpdir="${d}/tmp"
cachedir="${tmpdir}/cache"

rpmostree() {
    local manifest=$1

    echo "Building ${manifest}"
    rpm-ostree compose tree --repo="${tmprepo}" --cachedir="${cachedir}" --unified-core "${manifest}"
}

commit_overlay() {
    local name=$1
    local path=$2
    local respath=$(realpath "${path}")
    local git_timestamp="January 1 1970"

    echo -n "Committing ${name}: ${path} ... "
    ostree commit --repo="${tmprepo}" --tree=dir="${respath}" -b "${name}" \
        --owner-uid 0 --owner-gid 0 --no-xattrs --no-bindings --parent=none \
        --timestamp "${git_timestamp}"
}

prepare_compose_overlay() {
    local ovld="$d/overlay.d"
    if [ -d $ovld ]; then
         for n in "${ovld}"/*; do
             if ! [ -d "${n}" ]; then
                 continue
             fi

             local bn=$(basename "${n}")
             local ovlname="lirios-config-overlay-${bn}"
             commit_overlay "${ovlname}" "${n}"
             layers="${layers} ${ovlname}"
         done
    fi

    local overlays="$d/overlays"
    if [ -d $overlays ]; then
        for n in "${overlays}"/*; do
             if ! [ -d "${n}" ]; then
                 continue
             fi

             local bn=$(basename "${n}")
             local ovlname="lirios-bin-overlay-${bn}"
             commit_overlay "${ovlname}" "${n}"
        done
    fi
}

if ! [ -d "${cachedir}" ]; then
    mkdir -p "${cachedir}"
fi

if ! [ -d "${tmprepo}" ]; then
    mkdir -p "${tmprepo}"
    ostree init --repo="${tmprepo}" --mode=archive
fi

prepare_compose_overlay
rpmostree lirios-unstable-desktop.yaml
rpmostree lirios-unstable-live.yaml
