#!/bin/bash
# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

arch=$1
variant=$2

if [ -z "$arch" -o -z "$variant" ]; then
    echo "Usage: $0 [arch] [variant]"
    exit 1
fi

./build \
    --remote-url https://repo.liri.io/ostree/repo \
    --mirror-ref lirios/unstable/${arch}/${variant} \
    --treefile lirios-unstable-${variant}.yaml \
    --repodir repo --cachedir cache
