name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types:
      - rebuild

env:
  CI_GPG_KEYID: ${{ secrets.CI_GPG_KEYID }}
  CI_GPG_KEY: ${{ secrets.CI_GPG_KEY }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}

jobs:
  build-x86_64:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container:
      image: fedora:latest
      options: --privileged
    strategy:
      matrix:
        variant:
          - desktop
          - live
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -x
          dnf install -y dnf-plugins-core
          dnf copr enable -y plfiorini/liri-tools
          dnf install -y ostree-upload rpm-ostree gnupg2 pinentry selinux-policy selinux-policy-targeted policycoreutils
      - name: Import GPG key
        run: |
          .github/workflows/scripts/setup-gpg
          gpg --list-keys ${CI_GPG_KEYID}
      - name: Build
        run: |
          restorecon -R -v .
          .github/workflows/scripts/build x86_64 ${{ matrix.variant }}
      - name: Upload
        env:
            OSTREE_UPLOAD_TOKEN: ${{ secrets.OSTREE_UPLOAD_TOKEN }}
        run: |
          ostree-upload push \
            --address=${{ secrets.OSTREE_UPLOAD_URL }} \
            --branch=lirios/unstable/x86_64/${{ matrix.variant }}
